// Generated by https://quicktype.io

class CastResponse {
  int id;
  List<Cast> castList = [];

  CastResponse.fromJsonList(List<dynamic> jsonResponse) {
    jsonResponse.forEach((item) {
      final newCast = Cast.fromJsonObject(item);
      castList.add(newCast);
    });
  }
}

class Cast {
  bool adult;
  int gender;
  int id;
  String knownForDepartment;
  String name;
  String originalName;
  double popularity;
  String profilePath;
  int castId;
  String character;
  String creditId;
  int order;
  String department;
  String job;

  Cast({
    this.adult,
    this.gender,
    this.id,
    this.knownForDepartment,
    this.name,
    this.originalName,
    this.popularity,
    this.profilePath,
    this.castId,
    this.character,
    this.creditId,
    this.order,
    this.department,
    this.job,
  });

  Cast.fromJsonObject(Map<String, dynamic> json) {
    adult = json['adult'];
    gender = json['gender'];
    id = json['id'];
    knownForDepartment = json['known_for_department'];
    name = json['name'];
    originalName = json['original_name'];
    popularity = json['popularity'];
    profilePath = json['profile_path'];
    castId = json['castId'];
    character = json['character'];
    creditId = json['creditId'];
    order = json['order'];
    department = json['department'];
    job = json['job'];
  }

  String getPhotoURL() {
    if (profilePath == null) {
      return "https://st4.depositphotos.com/17828278/24401/v/600/depositphotos_244011872-stock-illustration-image-vector-symbol-missing-available.jpg";
    } else {
      return "https://image.tmdb.org/t/p/w500/$profilePath";
    }
  }
}
